pipelines:
  pipeline-demo:
    group: demo
    label_template: "${COUNT}"
    locking: off
    materials:
      app:
        git: https://github.com/jiangzijie123/pipeline-demo.git
        branch: master
    stages:
      - test:
          clean_workspace: true
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "./scripts/test.sh"
                    run_if: passed
      - build:
          clean_workspace: yes
          jobs:
            build:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "./scripts/build.sh"
                    run_if: passed
      - deploy:
          clean_workspace: yes
          jobs:
            deploy:
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "./scripts/deploy.sh"
                    run_if: passed
